# pip install git+https://github.com/LLaVA-VL/LLaVA-NeXT.git
# pip install tqdm

from llava.model.builder import load_pretrained_model
from llava.mm_utils import process_images, tokenizer_image_token
from llava.constants import IMAGE_TOKEN_INDEX, DEFAULT_IMAGE_TOKEN
from llava.conversation import conv_templates

from PIL import Image
from tqdm import tqdm
import copy
import torch
import warnings
import pandas as pd
import os
import json

warnings.filterwarnings("ignore")

# ==========================================
# 1. MODEL SETUP
# ==========================================
print("Loading LLaVA-Critic model... (This might take a minute)")
pretrained = "lmms-lab/llava-critic-7b"
model_name = "llava_qwen"
device = "cuda"
device_map = "auto"

tokenizer, model, image_processor, max_length = load_pretrained_model(
    pretrained,
    None,
    model_name,
    device_map=device_map
)
model.eval()

# ==========================================
# 2. LOAD EVALUATION DATA
# ==========================================
CSV_PATH = "evaluation_data.csv"
BASE_DIR = os.path.dirname(os.path.abspath(CSV_PATH))

df = pd.read_csv(CSV_PATH)

output_path = os.path.join(BASE_DIR, "llava_critic_results.jsonl")

# Open output file once in append mode — each row written immediately
success_count = 0
error_count = 0

with open(output_path, "a", encoding="utf-8") as out_f:

    for idx, row in tqdm(df.iterrows(), total=len(df), desc="Generating critiques", unit="img"):

        raw_path = str(row["omnigen2"]).strip().replace("\\", "/")
        image_path = os.path.normpath(os.path.join(BASE_DIR, raw_path))
        generation_prompt = row["description"]
        image_name = os.path.basename(image_path)

        # ---- IMAGE LOADING ----
        try:
            image = Image.open(image_path)
        except Exception as e:
            tqdm.write(f"  [ERROR] {image_name}: {e}")
            record = {
                "image_name": image_name,
                "description": generation_prompt,
                "critic": f"ERROR: Could not load image - {e}"
            }
            out_f.write(json.dumps(record, ensure_ascii=False) + "\n")
            out_f.flush()
            error_count += 1
            continue

        image_tensor = process_images([image], image_processor, model.config)
        image_tensor = [_image.to(dtype=torch.float16, device=device) for _image in image_tensor]

        # ---- PROMPT SETUP ----
        critic_prompt = f"""You are a visual-language critic. An image was generated by a diffusion model using this prompt:
[{generation_prompt}]

Analyze the image relative to the prompt.
Please:
1. Identify any deviations from the prompt and explain how they differ.
2. Note which keywords or phrases are poorly represented or misinterpreted.
3. Highlight any additional issues (e.g., artifacts, distortions, low detail) and their impact on quality.
Provide a clear, structured critique
ASSISTANT:\n"""

        # ---- FORMATTING & GENERATION ----
        conv_template = "qwen_1_5"
        conv = copy.deepcopy(conv_templates[conv_template])

        question = DEFAULT_IMAGE_TOKEN + "\n" + critic_prompt
        conv.append_message(conv.roles[0], question)
        conv.append_message(conv.roles[1], None)
        prompt_question = conv.get_prompt()

        input_ids = tokenizer_image_token(
            prompt_question, tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt"
        ).unsqueeze(0).to(device)
        image_sizes = [image.size]

        with torch.inference_mode():
            cont = model.generate(
                input_ids,
                images=image_tensor,
                image_sizes=image_sizes,
                do_sample=False,
                temperature=0,
                max_new_tokens=2048,
            )

        critic_text = tokenizer.batch_decode(cont, skip_special_tokens=True)[0]
        tqdm.write(f"  [OK] {image_name} ({len(critic_text)} chars)")

        record = {
            "image_name": image_name,
            "description": generation_prompt,
            "critic": critic_text
        }

        # Write + flush immediately — crash-safe
        out_f.write(json.dumps(record, ensure_ascii=False) + "\n")
        out_f.flush()

        success_count += 1

# ==========================================
# 4. DONE
# ==========================================
print(f"\n{'='*50}")
print(f"Done! Results saved to: {output_path}")
print(f"  Successful : {success_count}")
print(f"  Errors     : {error_count}")
print(f"{'='*50}")